[package]
name = "tiktok-personalization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
hyper = { version = "0.14.25", features = ["full"] }
pbkdf2 = { version = "0.12", features = ["simple"] }
rand_core = { version = "0.6", features = ["std"] }
rusqlite = { version = "0.29.0", features = ["bundled"] }
thirtyfour = "0.31.0"
tokio = { version = "1", features = ["full"] }
twilio = "1.0.2"
